import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`flex flex-col h-screen inter`}
      >
        <header className="flex justify-between self-center w-full max-w-[1000px] p-[40px]">
          <Link href="/">
            Home
          </Link>
          <Link href="/thoughts">
            Thoughts
          </Link>
          <Link href="#">
            Source
          </Link>
        </header>
        <section className="flex-1 flex flex-col">
          <main className="flex-1 p-[0_20px_40px_20px]">
            {children}
          </main>
          <footer className="flex flex-col gap-6 text-(--background) bg-(--foreground) p-[40px]">
            <span className="text-(--muted-foreground)">
              Fullstack application based on Spring Boot and Next.js
            </span>
            <div className="grid grid-cols-[repeat(2,_minmax(0,_250px))] gap-6">
              <div className="flex flex-col gap-3">
                <span className="font-semibold">
                  Socials
                </span>
                <Link href="#">
                  Github
                </Link>
                <Link href="#">
                  Telegram
                </Link>
              </div>
              <div className="flex flex-col gap-3">
                <span className="font-semibold">
                  Product
                </span>
                <Link href="#">
                  License
                </Link>
              </div>
            </div>
          </footer>
        </section>
      </body>
    </html>
  );
}
