import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`flex flex-col h-screen hanken-grotesk`}
      >
        <header className="flex justify-between self-center w-full max-w-[1000px] p-[40px]">
          <Link href="#">
            Home
          </Link>
          <Link href="#">
            Thoughts
          </Link>
          <Link href="#">
            Source
          </Link>
        </header>
        <section className="flex-1">
          <main className="h-full p-[0_20px_0_20px]">
            {children}
          </main>
          <footer className="flex flex-col gap-6 text-(--background) bg-(--foreground) p-[40px_40px_40px_40px]">
            <div className="flex flex-col gap-3">
              <span className="jetbrains-mono">
                Fullstack application based on Spring Boot and Next.js
              </span>
              <span className="text-(--muted-foreground)">
                Designed by @artndev
              </span>
            </div>
            <div className="grid grid-cols-[repeat(2,_minmax(0,_250px))] gap-6 jetbrains-mono">
              <div className="flex flex-col gap-3">
                <Link href="#">
                  Github
                </Link>
                <Link href="#">
                  Telegram
                </Link>
              </div>
              <div className="flex flex-col gap-3">
                <Link href="#">
                  CV.pdf
                </Link>
                <Link href="#">
                  LICENCE.md
                </Link>
              </div>
            </div>
          </footer>
        </section>
      </body>
    </html>
  );
}
