CREATE TABLE Articles (
    Id INT PRIMARY KEY AUTO_INCREMENT,
    Title VARCHAR(255),
    Subtitle VARCHAR(255),
    Content TEXT,
    Updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);