FROM maven:3.9.8-eclipse-temurin-21 AS build

COPY . .

ARG DB_HOST
ARG DB_NAME
ARG DB_PASSWORD
ARG DB_PORT
ARG DB_USERNAME
ARG VITE_ADMIN_AUTH_IP
ARG VITE_ADMIN_AUTH_TOKEN
ARG VITE_API_URL
ARG VITE_SOURCE_URL
ARG VITE_GITHUB_URL
ARG VITE_TELEGRAM_URL
ARG VITE_LICENSE_URL

ENV DB_HOST=$DB_HOST \
  DB_NAME=$DB_NAME \
  DB_PASSWORD=$DB_PASSWORD \
  DB_PORT=$DB_PORT \
  DB_USERNAME=$DB_USERNAME \ 
  VITE_ADMIN_AUTH_IP=$VITE_ADMIN_AUTH_IP \
  VITE_ADMIN_AUTH_TOKEN=$VITE_ADMIN_AUTH_TOKEN \
  VITE_API_URL=$VITE_API_URL \
  VITE_SOURCE_URL=$VITE_SOURCE_URL \
  VITE_GITHUB_URL=$VITE_GITHUB_URL \
  VITE_TELEGRAM_URL=$VITE_TELEGRAM_URL \
  VITE_LICENSE_URL=$VITE_LICENSE_URL

RUN mvn clean package -DskipTests

FROM openjdk:21
COPY --from=build /target/app.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]