FROM nginx:alpine

ARG ADMIN_USERNAME
ARG ADMIN_PASSWORD

RUN apk add --no-cache apache2-utils
RUN htpasswd -bc /etc/nginx/.htpasswd "$ADMIN_USERNAME" "$ADMIN_PASSWORD"

COPY /nginx/nginx.conf /etc/nginx/conf.d/default.conf
COPY /artndev-blog/target/classes/static /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
