FROM maven:3.9.8-eclipse-temurin-21 AS build

COPY . .

ARG VITE_ADMIN_AUTH_TOKEN
ARG VITE_API_URL
ARG VITE_SOURCE_URL
ARG VITE_GITHUB_URL
ARG VITE_TELEGRAM_URL
ARG VITE_LICENSE_URL

ENV VITE_ADMIN_AUTH_TOKEN=$VITE_ADMIN_AUTH_TOKEN \
  VITE_API_URL=$VITE_API_URL \
  VITE_SOURCE_URL=$VITE_SOURCE_URL \
  VITE_GITHUB_URL=$VITE_GITHUB_URL \
  VITE_TELEGRAM_URL=$VITE_TELEGRAM_URL \
  VITE_LICENSE_URL=$VITE_LICENSE_URL

RUN mvn clean package -DskipTests

FROM openjdk:21
COPY --from=build /target/app.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]