CREATE TABLE Articles (
    Id INT AUTO_INCREMENT,
    Title VARCHAR(255) NOT NULL,
    Subtitle VARCHAR(255) NOT NULL,
    Content TEXT NOT NULL,
    Updated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (Id)
);