CREATE TABLE Articles (
    Id INT AUTO_INCREMENT,
    Title TEXT NOT NULL,
    Subtitle TEXT NOT NULL,
    Content TEXT NOT NULL,
    Tags TEXT NOT NULL,
    Updated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (Id)
);